[env:native]
platform = native
test_framework = unity
test_build_src = yes
lib_deps =
    mea-core=symlink://../mea-core
    mea-protocol=symlink://../mea-protocol
build_unflags = -std=gnu++11
build_flags =
    -std=gnu++17
    -Wall
    -Wextra
    -Wpedantic
    -Wconversion
    -Wshadow
    -Werror
    -Wno-error=sign-conversion
    -fsanitize=address,undefined
    -fno-omit-frame-pointer
